### ISSUE TITLE
PHP errors when sincronize

### ISSUE THREAD

**Issue by jjmg84** [pluginsGLPI/ocsinventoryng#336] opened 2022-10-31 12:11 UTC
Hi, when sincronize we have these error recurently , too many times on log:

2022-10-31 13:04:43] glpiphplog.WARNING:   *** PHP Warning (2): preg_match_all(): Unknown modifier ']' in /var/www/glpi10/src/RuleCriteria.php at line 494
  Backtrace :
  src/RuleCriteria.php:494                           preg_match_all()
  src/Rule.php:1702                                  RuleCriteria::match()
  src/Rule.php:1624                                  Rule->checkCriteria()
  src/Rule.php:1507                                  Rule->checkCriterias()
  src/RuleCollection.php:1591                        Rule->process()
  src/CommonDBTM.php:5630                            RuleCollection->processAllRules()
  src/CommonDBTM.php:1595                            CommonDBTM->assetBusinessRules()
  plugins/ocsinventoryng/inc/hardware.class.php:251  CommonDBTM->update()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:901 PluginOcsinventoryngHardware::updateComputerHardware()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:471 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:448 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:297 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:179 SecondPass()

Versions:
- ocsinventoryng : 2.0.2
- The version of your GLPI : 10.0.0.3
- The steps to reproduce your issue: Force to sincronize plugin and watch console or logs

Thanks in advance, if more information is needed please ask it

**Comment by tsmr** [comment] 2022-11-05 14:29
There is a problem with a rule of your rule engine

**Comment by jjmg84** [comment] 2022-11-09 11:24
> There is a problem with a rule of your rule engine

We review all rules and all seems to be okay, and with GLPI 9 it was working allright, how we can debug the rule engine?

Thanks,

**Comment by eabreu218** [comment] 2022-11-22 17:03
I had the same error messages on a server upgraded from 9.5 to 10.0.5

I just found out there was a problem on this server with rule "Business rules for assets / Multiple users: assign to the first".
3rd Criterion for that rule was : 'Alternate username  regular expression matches  /(.*)[,|/]/'
That pattern should be '/(.*)[,|\/]/'

I believe this problem must be caused by some upgrade script: 
- on a GLPI 10.0.5 server installed "from scratch", the pattern is correct
- on the old GLPI 9.5 server, the pattern was just '/(.*),/', without the alternative part

**Closed** 2022-11-26 09:14 UTC
